Rails:
  Enabled: true
AllCops:
  TargetRubyVersion: 2.4
Metrics/LineLength:
  Max: 120
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Exclude:
    - 'app/controllers/beach_api_core/concerns/v1/apipie_concern.rb'
    - '**/*_spec.rb'
    - 'spec/factories/**/*'
    - 'spec/dummy/db/migrate/*'
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'lib/admin/*'
Documentation:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': ()
    '%w': ()
AllCops:
  Exclude:
    - 'spec/dummy/db/schema.rb'