default: &default
  adapter: postgresql
  pool: 10
  timeout: 5000

development:
  <<: *default
  database: beach_api_core_development

test: &test
  <<: *default
  database: beach_api_core_test<%= ENV['TEST_ENV_NUMBER']%>

production:
  <<: *default
  database: beach_api_core_production
