class CreateBeachApiCoreActionsControllers < ActiveRecord::Migration[5.1]
  def change
    create_table :beach_api_core_actions_controllers do |t|
      t.string :name
      t.references :controllers_service,
                   foreign_key: { to_table: :beach_api_core_controllers_services },
                   # need to specify index name because of too long autogenerated index name
                   index: { name: 'index_beach_api_core_actions_cont_on_controllers_service_id' }, null: false

      t.timestamps
    end
  end
end
